# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(related_name='friends', to='login.User'),
        ),
    ]
